INSERT INTO USER_ROLES (ROLE) VALUES ('USER_ROLE');
INSERT INTO USER_ROLES (ROLE) VALUES ('AUTHOR_ROLE');
INSERT INTO USER_ROLES (ROLE) VALUES ('REVIEWER_ROLE');
INSERT INTO USER_ROLES (ROLE) VALUES ('EDITOR_ROLE');
INSERT INTO USER_ROLES (ROLE) VALUES ('ADMIN_ROLE');